title: "Affiliates"
email: wowthemesnet@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: Eason
    display_name: 暂停空间
    avatar: 'assets/images/sal.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/zantingkongjian
    description: "暂停空间"
  john:
    name: Eason
    display_name: 暂停空间
    avatar: 'assets/images/john.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "暂停空间"

# Social
social:
  instagram: 
  facebook: 
  twitter: https://twitter.com/zantingkongjian

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
